android.useAndroidX=true
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m
org.gradle.java.home=D\:/Android-studio/jbr
kapt.incremental.apt=true
kapt.use.worker.api=true
org.gradle.vfs.watch=false
android.dependency.useConstraints=true
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE
android.dependency.excludeLibraryComponentsFromConstraints=true
android.r8.strictFullModeForKeepRules=false