android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m
# Java 25 (in JBR) is currently incompatible with Gradle 8.14.4 (supports up to Java 24).
# If you upgrade Gradle in the future, you can try re-enabling this line.
# org.gradle.java.home=D\:/Android-studio/jbr
kapt.incremental.apt=false
kapt.use.worker.api=false
org.gradle.vfs.watch=false
